; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for CoinHeist:

; to see the correct usage look at the file, "musicMacro.s"

;; IMPORTS AND EXPORTS
.export _music_data_coinheist:=music_data_coinheist
.export _sounds=sounds

; ------------------------------------------------------------------------

music_data_coinheist:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : CoinHeist - Start
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_coinheist
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env4,@env0 ; 00 : Lead
	.word @env5,@env2,@env3,@env0 ; 01 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$08
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $00,$ce,$ca,$c5,$c0,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $24, $8b, $24, $8b, $29, $97, $24, $97, $00, $97, $24, $89, $24, $8b, $29, $97, $24, $97, $00, $97, $26, $99, $28, $97
	.byte $24, $97, $00, $97, $26, $97, $28, $97, $26, $89, $28, $8b, $26, $8b, $28, $89, $48, $24, $8b, $24, $8b, $29, $97, $24
	.byte $97, $00, $97, $24, $97, $2b, $97, $26, $97, $00, $97, $26, $99, $28, $97, $24, $97, $00, $97, $26, $89, $28, $8b, $26
	.byte $8b, $28, $89, $26, $89, $28, $8b, $26, $8b, $28, $89, $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch4:
@song0ch2:
@song0ch1:
@song0ch1loop:
@song0ref123:
	.byte $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3
	.byte $41, $14
	.word @song0ref123
	.byte $41, $14
	.word @song0ref123
	.byte $ff, $ff, $ff, $a3, $42
	.word @song0ch1loop
@song0ch3:
@song0ch3loop:
	.byte $00, $99, $82
@song0ref160:
	.byte $32, $97, $00, $97, $32, $97, $00, $97, $32, $97, $00, $97, $32, $97, $00, $99, $32, $97, $00, $97, $32, $97, $00, $97
	.byte $32, $97, $00, $97, $32, $97, $00, $99
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $20
	.word @song0ref160
	.byte $41, $1e
	.word @song0ref160
	.byte $42
	.word @song0ch3loop


; SFX
; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

sounds:
	.word @pal
	.word @pal
@pal:
	.word @sfx_pal_coinpickup
	.word @sfx_pal_abilitypickup
	.word @sfx_pal_gunshot
	.word @sfx_pal_abilityusage
	.word @sfx_pal_lose
	.word @sfx_pal_win
	.word @sfx_pal_bomb
	.word @sfx_pal_dash

@sfx_pal_coinpickup:
	.byte $87,$31,$88,$00,$86,$8e,$89,$f0,$01,$87,$26,$86,$8a,$01,$87,$20
	.byte $86,$85,$01,$87,$31,$86,$80,$01,$87,$26,$01,$87,$31,$86,$8e,$01
	.byte $87,$26,$86,$8a,$01,$87,$20,$86,$85,$01,$87,$31,$86,$80,$01,$87
	.byte $26,$01,$86,$8e,$01,$87,$1e,$86,$8a,$01,$87,$19,$86,$85,$01,$87
	.byte $26,$86,$80,$01,$87,$1e,$06,$87,$2b,$86,$8e,$01,$87,$22,$86,$8a
	.byte $01,$87,$1d,$86,$85,$01,$87,$2b,$86,$80,$01,$87,$22,$06,$81,$6e
	.byte $82,$00,$80,$7e,$01,$81,$57,$80,$7a,$01,$81,$49,$80,$75,$01,$81
	.byte $6e,$00
@sfx_pal_abilitypickup:
	.byte $81,$94,$82,$00,$80,$7e,$89,$f0,$01,$81,$75,$80,$7a,$01,$81,$62
	.byte $80,$75,$01,$81,$94,$80,$70,$01,$81,$75,$01,$81,$b0,$80,$7e,$01
	.byte $81,$8b,$80,$7a,$01,$81,$75,$80,$75,$01,$81,$b0,$80,$70,$01,$81
	.byte $8b,$01,$81,$b0,$80,$7e,$01,$81,$8b,$80,$7a,$01,$81,$75,$80,$75
	.byte $01,$81,$b0,$80,$70,$01,$81,$8b,$06,$81,$84,$80,$7e,$01,$81,$68
	.byte $80,$7a,$01,$81,$57,$80,$75,$01,$81,$84,$00
@sfx_pal_gunshot:
	.byte $8a,$85,$89,$3e,$01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$8a,$88
	.byte $89,$3e,$01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$8a,$86,$89,$3e
	.byte $01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$89,$3e,$01,$89,$3a,$01
	.byte $89,$35,$01,$00
@sfx_pal_abilityusage:
	.byte $87,$6e,$88,$00,$86,$8e,$89,$f0,$01,$87,$57,$86,$8a,$01,$87,$49
	.byte $86,$85,$01,$87,$6e,$86,$80,$01,$87,$57,$01,$87,$8b,$86,$8e,$01
	.byte $87,$6e,$86,$8a,$01,$87,$5d,$86,$85,$01,$87,$8b,$86,$80,$01,$87
	.byte $6e,$01,$87,$8b,$86,$8e,$01,$87,$6e,$86,$8a,$01,$87,$5d,$86,$85
	.byte $01,$87,$8b,$86,$80,$01,$87,$6e,$06,$86,$8e,$01,$87,$57,$86,$8a
	.byte $01,$87,$49,$86,$85,$01,$87,$6e,$00
@sfx_pal_lose:
	.byte $87,$8b,$88,$00,$86,$8f,$89,$f0,$0a,$87,$b0,$0a,$87,$c6,$0a,$87
	.byte $ba,$0a,$87,$94,$14,$87,$a6,$14,$87,$de,$14,$00
@sfx_pal_win:
	.byte $89,$f0,$00
@sfx_pal_bomb:
	.byte $8a,$8d,$89,$3e,$01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$8a,$8b
	.byte $89,$3e,$01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$8a,$8d,$89,$3e
	.byte $01,$89,$3a,$01,$89,$35,$01,$89,$30,$02,$8a,$8f,$89,$3e,$01,$89
	.byte $3a,$01,$89,$35,$01,$00
@sfx_pal_dash:
	.byte $89,$f0,$00

.export sounds
